[package]
name = "camera_capture"
version = "0.3.0"
authors = ["Oliver Schneider <git-spam-no-reply9815368754983@oli-obk.de>"]
license = "MIT"
description = "capture webcam images on linux and windows"
keywords = ["webcam", "v4l", "capture", "camera", "mf"]
repository = "https://github.com/oli-obk/camera_capture"

build = "build.rs"

[features]
default = ["rgb-format"]

luma-format = []
rgb-format = []
rgba-format = []

[build-dependencies]
pkg-config = "0.3.8"

[dependencies]
image = "0.14.0"

[target.'cfg(windows)'.dependencies]
escapi = "3.0.5"
lazy_static = "0.2.8"

[target.'cfg(unix)'.dependencies]
rscam = "0.5.2"

[dev-dependencies]
piston_window = "0.67.0"
piston-texture = "0.5.0"
fps_counter = "0.2.0"
